
class BasePermissionError(Exception): ...

class NotAllowedError(BasePermissionError): ...
class SetupPermissionError(BasePermissionError): ...
class SetupUserError(BasePermissionError): ...
class SetupImageError(BasePermissionError): ...